bookpulse/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/auth/', include('user.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls')),
]

urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
    name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views
from .views import ProductSearchListView


app_name = 'shop'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('search/', ProductSearchListView.as_view(), name='product-search'),
    path('book/<str:isbn>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('interaction/<str:isbn>/', views.register_interaction, name='register_interaction'),
    path('recommendations/<int:user_id>/', views.recommend_books_view, name='recommendations'),
    #path('categories/', views.category_list, name='category_list'),
    path('categories/<int:category_id>/', views.books_by_category, name='books_by_category'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 5)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, 
                                      coerce=int, 
                                      widget=forms.Select(attrs={'class': 'form qty', }))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart

from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, 
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
        return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item['quantity'],
            'override':True
        })
    return render(request, 'cart/detail.html', {'cart':cart})

cart/templates/cart/detail.html
{% extends 'root/_base.html' %}
{% load static %}
{% block title %} Shopping cart {% endblock%}
{% block style %} <link rel="stylesheet" href="{% static 'css/homepage.css' %}"> {% endblock %}

    {% block content %}
    <div class="container mt-5">
        <h1 class="h4">Your shopping cart</h1>
        <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">Image</th>
                <th scope="col">Book</th>
                <th scope="col">QTY</th>
                <th scope="col">Unit Price</th>
                <th scope="col">Price</th>
                <th scope="col">Remove</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for item in cart %}
                {% with product=item.product %}
              <tr>
                <!--th scope="row">1</th-->
                <td>
                    <a href="{{ product.cover_photo_url }}" class="thumbnail">
                        <img src="{% if product.cover_photo_url %}{{ product.cover_photo_url }}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}" style="
                        width: 50px; /* Set the desired width */
                        height: 50px; /* Set the desired height */
                        object-fit: cover;">
                    </a>
                </td>
                

                <td>{{ product.title|truncatechars:20 }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity}}
                        {{ item.update_quantity_form.override}}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>

                
                <td class="num">(USD)$ {{ item.price }}</td>
                <td class="num">(USD)$ {{ item.total_price }}</td>
                
                <td>
                    <form action="{% url 'cart:cart_remove' product.id %}"
                    method="post">
                        <input type="submit" value="Remove">
                        {% csrf_token %}
                    </form>
                </td>
              </tr>

              
              {% endwith %}
              {% endfor %}

              <tr class="total">
                  <td>Total</td>
                  <td colspan="4"></td>
                  <td class="num">(USD)$ {{ cart.get_total_price }}</td>
              </tr>
            </tbody>
         </table>

        <p class="text-right">
            <a href="{% url 'shop:index' %}" class="buttonlight btn-">Continue shopping</a>
            <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
        </p>
    </div>
{% endblock %}