bookpulse/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/auth/', include('user.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls')),
]

urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
    name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views
from .views import ProductSearchListView


app_name = 'shop'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('search/', ProductSearchListView.as_view(), name='product-search'),
    path('book/<str:isbn>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('interaction/<str:isbn>/', views.register_interaction, name='register_interaction'),
    path('recommendations/<int:user_id>/', views.recommend_books_view, name='recommendations'),
    #path('categories/', views.category_list, name='category_list'),
    path('categories/<int:category_id>/', views.books_by_category, name='books_by_category'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    #path('register_form/', views.RegistrationFormView, name='registration_form'),
    path('register/', views.registerView, name='register'),
    path('profile/', views.ProfileView, name='profile'),
    path('login/', views.LoginView, name='login'),
    path('logout/', views.LogoutView, name='logout')
]

templates/root/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Bookpulse - {% block title %} Home {% endblock %}</title>

    <!-- Custom Links -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/splide.min.css' %}" rel="stylesheet">
    {% block style %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" >
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.3/dist/tailwind.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />


    <!-- Google Font Link-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Lora:ital,wght@0,400..700;1,400..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Pacifico&display=swap" rel="stylesheet">
</head>


<body>
    {% include 'root/_header.html' %}
    {% block content %}{% endblock %}
    {% include 'root/_footer.html' %}
</body>

    <!-- Custom Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e04e3e1844.js"></script>
    <!---script src="{% static 'js/splide.min.js' %}"></!---script-->
    <script src="{% static 'js/root.js' %}"></script>
    <script src="{% static 'js/websocket.js' %}"></script>
    <script src="{% static 'js/daphane_socket.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>

    <!--script>
        document.addEventListener( 'DOMContentLoaded', function() {
          var splide = new Splide( '.splide' );
          splide.mount();
        } );
    </!--script-->
</html>

templates/root/_footer.html
{% block content %}
<div class="container">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Recommended</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contacts</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
      <p class="text-center text-muted">&copy; 2024 BookPulse, Inc</p>
    </footer>
  </div>
{% endblock %}

templates/root/_header.html
{% block content %}
<div class="container-fluid sticky-top header-nav" id="headerNav">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="text-muted blog-header-logo" href="{% url 'shop:index' %}">
          <h3>Bookpulse</h3>
        </a>
      </div>
      <div class="col-4 text-center d-none d-md-block">
        <form method="GET" action="{% url 'shop:product-search' %}">
          <div class="form-inline search-form">
            <div class="input-group">
              <button type="submit" class="input-group-prepend btn btn-sm">
                <span class="input-group-text search-icon">
                  <i class="fas fa-search"></i>
                </span>
              </button>
              <input type="text" class="form-control custom-input" name="q" id="" value="{{ request.GET.q }}"
                placeholder="Search for products...">
        </form>
      </div>
    </div>
</div>
<div class="col-4 d-flex justify-content-end align-items-center">
  <div class="custom-dropdown btn btn-sm ">
    {% if user.is_authenticated %}
    <button class="custom-dropdown-button py-1 px-2 d-lg-inline d-md-inline d-sm-inline d-xs-inline">{{user.email}} <i
        class="fas fa-caret-down"></i></button>
    <div class="custom-dropdown-content">
      <a href="{% url 'user:profile' %}">Account</a>
      <a href="#">Wishlist <span> - 71</span></a>
      <a href="#">Help & Support</a>
      <a href="{% url 'user:logout' %}">Logout</a>
    </div>
    {% else %}
    <button class="custom-dropdown-button py-1 px-2 d-lg-inline d-md-inline d-sm-inline d-xs-inline">Create Account <i
        class="fas fa-caret-down"></i></button>
    <div class="custom-dropdown-content">
      <a href="{% url 'user:register' %}">Sign Up</a>
      <a href="#">Wishlist <span> - 20</span></a>
      <a href="#">Help & Support</a>
      <a href="{% url 'user:login' %}">Sign In</a>
    </div>
    {% endif %}
  </div>
  <a href="{% url 'cart:cart_detail' %}" class="cart-icon">
    <i class="fas fa-shopping-cart"></i>
    <span class="item-count">{{ request.session.cart|length }}</span>
  </a>

</div>
</div>
</header>


<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    {% if user.is_authenticated %}
      <a class="p-2 nav-item" href="{% url 'shop:recommendations' user_id=request.user.id %}">Recommended</a>
    {% endif %}

    {% for category in categories %}
      <a href="{% url 'shop:books_by_category' category.id %}" class="p-2 nav-item">{{ category.name }}</a>
      {% empty %}
      <h3>No categories available.</h3>
    {% endfor %}
  </nav>
</div>
</div>
{% endblock %}