bookpulse/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/auth/', include('user.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls')),
]

urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
    name='cart_remove'),
]

payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook')
]

shop/urls.py
from django.urls import path
from . import views
from .views import ProductSearchListView


app_name = 'shop'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='index'),
    path('search/', ProductSearchListView.as_view(), name='product-search'),
    path('book/<str:isbn>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('interaction/<str:isbn>/', views.register_interaction, name='register_interaction'),
    path('recommendations/<int:user_id>/', views.recommend_books_view, name='recommendations'),
    #path('categories/', views.category_list, name='category_list'),
    path('categories/<int:category_id>/', views.books_by_category, name='books_by_category'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render
from decimal import Decimal
from django.conf import settings
from django.shortcuts import render, redirect, reverse, get_object_or_404
import stripe
from orders.models import Order



# Create the stripe instance
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))

        # stripe checkout session
        session_data = {
            'mode':'payment',
            'client_reference_id':order.id,
            'success_url':success_url,
            'cancel_url':cancel_url,
            'line_items':[]
        }

        # add order items to the stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency':'usd',
                    'product_data':{
                        'name':item.product.title,
                        'images':["http://images.amazon.com/images/P/1561568805.01.MZZZZZZZ.jpg"]
                    },
                },
                'quantity': item.quantity,
            })

        #create stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        # redirect to stripe payment form
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())
    

def payment_completed(request):
    return render(request, 'payment/completed.html')

def payment_canceled(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends 'root/_base.html' %}
{% load static %}
{% block title %} Payment cancelled {% endblock%}
{% block style %} <link rel="stylesheet" href="{% static 'css/homepage.css' %}"> {% endblock %}


{% block content %}
    <div class="container mt-5">
        <h1 class="text-danger">Payment Failed</h1>
        <p>There was a problem processing your payment.</p>
    </div>
{% endblock %}

payment/templates/payment/completed.html
{% extends 'root/_base.html' %}
{% load static %}
{% block title %} Payment successful {% endblock%}
{% block style %} <link rel="stylesheet" href="{% static 'css/homepage.css' %}"> {% endblock %}



{% block content %}
    <div class="container mt-5">
        <h3 class="text-success">Payment Successful</h3>
        <p>Your payment has been processed successfully.</p>
        <a href="{% url 'shop:index' %}" class="btn btn-sm text-white">Return to HomePage</a>
    </div>
{% endblock %}

payment/templates/payment/process.html
{% extends 'root/_base.html' %}
{% load static %}
{% block title %} Order {% endblock%}
{% block style %} <link rel="stylesheet" href="{% static 'css/homepage.css' %}"> {% endblock %}


{% block content %}

    
    <div class="container mt-4">
        <h3 class="text-bold">Order summary</h3>
        <table class="table cart table-striped mt-3">
        <thead>
        <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        </tr>
        </thead>

        <tbody>
            {% for item in order.items.all %}
            <tr class="row{% cycle "1" "2" %}">
                <td>
                    <img src="{{ item.product.cover_photo_url }}">
                </td>
                <td>{{ item.product.title }}</td>
                <td class="num">${{ item.price }}</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num">${{ item.get_cost }}</td>
            </tr>
            {% endfor %}

            <tr class="total">
                <td colspan="4">Total</td>
                <td class="num">${{ order.get_total_cost }}</td>
            </tr>
        </tbody>
        </table>


        <form action="{% url 'payment:process' %}" method="post" class="btn btn-sm">
            <input type="submit" value="Pay now" class="btn btn-sm text-white">
            {% csrf_token %}
        </form>
    </div>
{% endblock %}